server:
  port: 80

eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
  client:
    #eureka client刷新本地缓存时间
    #默认30s
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://localhost:8001/eureka/

spring:
  application:
    name: HMCLOUD-CLIENT80
feign:
  hystrix:
    enabled: true
  httpclient:
    connection-timeout: 5000

logging:
  level:
    com.hm.client80.call.HmCloudCallPayment: debug
ribbon:
  ReadTimeout : 5000
  ConnectTimeout : 5000
