
server:
  port: 8086
spring:
  application:
    name: HMCLOUD-RABBITMQ-CSTOMER
  cloud:
    stream:
      binders:  #配置要绑定的rabbitmq服务信息
        defaultRabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest
      bindings:
        input:
          destination: studyExchange
          content-type: application/json

eureka:
  instance:
    hostname: cloud-config-service
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
    instance-id: send-80856.com

  client:
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://localhost:8001/eureka/