server:
  port: 8083

spring:
  application:
    name: HMCLOUD-CONFIG-CENTER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/peihaoming/hmconfig.git
          default-label: main
          search-paths: hmconfig


eureka:
  instance:
    hostname: cloud-config-service
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15

  client:
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://localhost:8001/eureka/
