server:
  port: 8401

spring:
  application:
    name: CLOUD-ALIBABA-SNETINEL
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8858
management:
  endpoints:
    web:
      exposure:
        include: '*'
